# Generated by Django 5.0.3 on 2024-03-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_oneproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneproduct',
            name='image',
            field=models.ImageField(upload_to='uploads/oneproduct/'),
        ),
    ]
