# Generated by Django 5.0.3 on 2024-04-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='confirm_passwod',
        ),
    ]
