# Generated by Django 5.0.3 on 2024-04-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_author_product_book_formate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsproduct',
            name='author',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bsproduct',
            name='book_formate',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bsproduct',
            name='edition_language',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bsproduct',
            name='isbn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='bsproduct',
            name='publisher',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='fourproduct',
            name='author',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='fourproduct',
            name='book_formate',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='fourproduct',
            name='edition_language',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='fourproduct',
            name='isbn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='fourproduct',
            name='publisher',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='oneproduct',
            name='author',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='oneproduct',
            name='book_formate',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='oneproduct',
            name='edition_language',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='oneproduct',
            name='isbn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='oneproduct',
            name='publisher',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='thirdproduct',
            name='author',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='thirdproduct',
            name='book_formate',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='thirdproduct',
            name='edition_language',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='thirdproduct',
            name='isbn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='thirdproduct',
            name='publisher',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='twoproduct',
            name='author',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='twoproduct',
            name='book_formate',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='twoproduct',
            name='edition_language',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='twoproduct',
            name='isbn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='twoproduct',
            name='publisher',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bsproduct',
            name='image',
            field=models.ImageField(upload_to='uploads/bsproduct/'),
        ),
    ]
