# Generated by Django 5.0.3 on 2024-04-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_bsproduct_author_bsproduct_book_formate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsproduct',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='fourproduct',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='oneproduct',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='thirdproduct',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='twoproduct',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
