# Generated by Django 5.0.3 on 2024-04-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_bsproduct_author_alter_fourproduct_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsproduct',
            name='publisher',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='fourproduct',
            name='publisher',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='oneproduct',
            name='publisher',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='publisher',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='thirdproduct',
            name='publisher',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='twoproduct',
            name='publisher',
            field=models.CharField(default='', max_length=30),
        ),
    ]
