# Generated by Django 5.0.3 on 2024-04-07 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_rename_register_registered_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='zipcode',
            new_name='pincode',
        ),
    ]
