# Generated by Django 5.0.3 on 2024-04-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_rename_zipcode_profile_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_full_name', models.CharField(max_length=255)),
                ('shipping_email', models.CharField(max_length=255)),
                ('shipping_address1', models.CharField(max_length=255)),
                ('shipping_address2', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_city', models.CharField(max_length=255)),
                ('shipping_state', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_pincode', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_country', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Registered_user',
        ),
    ]
