# Generated by Django 5.0.3 on 2024-04-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_signupform_delete_registered_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupform',
            old_name='shipping_address1',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='signupform',
            old_name='shipping_city',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='signupform',
            old_name='shipping_country',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='signupform',
            old_name='shipping_email',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='signupform',
            old_name='shipping_full_name',
            new_name='password2',
        ),
        migrations.RemoveField(
            model_name='signupform',
            name='shipping_address2',
        ),
        migrations.RemoveField(
            model_name='signupform',
            name='shipping_pincode',
        ),
        migrations.RemoveField(
            model_name='signupform',
            name='shipping_state',
        ),
        migrations.AddField(
            model_name='signupform',
            name='user',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
