# Generated by Django 5.0.3 on 2024-04-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_rename_shipping_address1_signupform_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUpForm',
        ),
    ]
