# Generated by Django 5.0.3 on 2024-04-07 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_alter_shippingaddress_shipping_address2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_zipcode',
            new_name='shipping_pincode',
        ),
    ]
