# Generated by Django 5.0.3 on 2024-04-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_shipping_zipcode_shippingaddress_shipping_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=255)),
                ('card_exp_date', models.CharField(max_length=255)),
                ('card_cvv_number', models.CharField(blank=True, max_length=255, null=True)),
                ('card_address1', models.CharField(max_length=255)),
                ('card_address2', models.CharField(blank=True, max_length=255, null=True)),
                ('card_city', models.CharField(blank=True, max_length=255, null=True)),
                ('card_state', models.CharField(max_length=255)),
                ('card_pincode', models.CharField(max_length=255)),
                ('card_country', models.CharField(max_length=255)),
            ],
        ),
    ]
