# Generated by Django 5.0.3 on 2024-05-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_paymentform'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
