# Generated by Django 5.0.3 on 2024-05-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_orderitem_date_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='date_ordered',
            field=models.DateField(auto_now_add=True),
        ),
    ]
