# Generated by Django 5.0.3 on 2024-05-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_orderitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
