# Generated by Django 5.0.3 on 2024-05-19 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_orderitem_shipped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='total',
            new_name='amount_paid',
        ),
    ]
